kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: 'ODH-TEC Workbench Image (from: https://quay.io/repository/rh-aiservices-bu/odh-tec?tab=tags'
    opendatahub.io/notebook-image-order: '02'
    opendatahub.io/notebook-image-url: 'https://quay.io/repository/rh-aiservices-bu/odh-tec?tab=tags'
    opendatahub.io/notebook-image-name: 'Kickstart Custom Image: ODH-TEC Workbench'
    opendatahub.io/recommended-accelerators: '[]'
  name: kickstart-image-odh-tec-workbench
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 1.2.1
      annotations:
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "ODH-TEC","version": "v1.2.1"}
          ]
        opendatahub.io/notebook-software: |
          [
            {"name": "ODH-TEC", "version": "v1.2.1"}
          ]
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/odh-tec:1.2.1'
        opendatahub.io/workbench-image-recommended: 'true'
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/odh-tec:1.2.1'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: 1.2.0
      annotations:
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "ODH-TEC","version": "v1.2.0"}
          ]
        opendatahub.io/notebook-software: |
          [
            {"name": "ODH-TEC", "version": "v1.2.0"}
          ]
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/odh-tec:1.2.0'
        opendatahub.io/workbench-image-recommended: 'false'
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/odh-tec:1.2.0'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: 1.1.2
      annotations:
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "ODH-TEC","version": "v1.1.2"}
          ]
        opendatahub.io/notebook-software: |
          [
            {"name": "ODH-TEC", "version": "v1.1.2"}
          ]
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/odh-tec:1.1.2'
        opendatahub.io/workbench-image-recommended: 'false'
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/odh-tec:1.1.2'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
